Spring security realization
Organization2374/Task-7 pull request #1
Opened 2024-08-22 18:55 UTC by Skwotik

Task 3.1.2

2024-08-23 18:06 UTC, pdasilem requested changes

2024-08-23 18:06 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/UserController.java
> +public class UserController {
админконтроллер?

2024-08-23 18:06 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/RegistrationController.java
> +public class RegistrationController {
юзерконтроллер?
убрать из него лишнее

2024-08-23 18:06 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/models/Role.java
> +public enum Role implements GrantedAuthority {
это должен быть класс

2024-08-23 18:06 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/models/User.java
> +    @ElementCollection(targetClass = Role.class, fetch = FetchType.EAGER)
избавиться от игер

2024-08-23 20:42 UTC, Skwotik commented
Контроллеры переименованы, теперь каждый занимается своими вещами
Role преобразован в class вместо enum
Избавился от EAGER при загрузке ролей, инициализация ролей при логине перенесена в сервис в метод loadUserByUsername()

2024-08-24 16:38 UTC, pdasilem approved these changes

2024-08-24 16:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/UserController.java
> +    @GetMapping("/user")
можно вынести юзер в класс.

2024-08-24 23:14 UTC, merged